#!/bin/bash

# Leandro Sehnem Heck (leoheck@gmail.com)

# PRINTER CONFIG

key="$1"

install_cmd()
{
	SCRIPTDIR=$1

	echo "  - Configuring printers"

	# BACKUP
	if [ ! -f /etc/cups/printers.conf.bkp ]; then
		if [ -f /etc/cups/printers.conf ]; then
			cp /etc/cups/printers.conf /etc/cups/printers.conf.bkp
		fi
	else
		cp /etc/cups/printers.conf.bkp /etc/cups/printers.conf
	fi

	# Acho que esse arquivo tem que ter o mesmo nome da impressora
	cp -f $SCRIPTDIR/cups/COPY3212.ppd /etc/cups/ppd/COPY3212.ppd

	service cups stop &> /dev/null

	#===========================
	read -r -d '' PRINTERS <<-EOM

	# Printer configuration file for CUPS v1.7.2
	# Written by cupsd
	# DO NOT EDIT THIS FILE WHEN CUPSD IS RUNNING

	<Printer PDF>
	UUID urn:uuid:0888f27b-befd-30c7-5b0a-1ff0aea8a8d2
	Info PDF Printer
	DeviceURI cups-pdf:/
	PPDTimeStamp *
	State Idle
	StateTime 1420820769
	Type 8450124
	Accepting Yes
	Shared No
	ColorManaged Yes
	JobSheets none none
	QuotaPeriod 0
	PageLimit 0
	KLimit 0
	OpPolicy default
	ErrorPolicy retry-job
	</Printer>

	<Printer COPY3212>
	UUID urn:uuid:8b6eb276-0fd5-371a-4e15-f7815998d338
	AuthInfoRequired username,password
	Info COPY3212
	Location Sala  (COPY3212 Processores)
	DeviceURI smb://10.40.110.105/impressora
	PPDTimeStamp *
	State Idle
	StateTime 1464808849
	Type 12619988
	Accepting Yes
	Shared No
	ColorManaged Yes
	JobSheets none none
	QuotaPeriod 0
	PageLimit 0
	KLimit 0
	OpPolicy authenticated
	ErrorPolicy retry-job
	Option fitplot True
	Option media 1
	Option media-col media-bottom-margin
	Option output-bin 0
	Option print-color-mode color
	Option print-quality 5
	Option sides two-sided-long-edge
	</Printer>

	EOM
	#===========================

	echo "$PRINTERS" > /etc/cups/printers.conf

	service cups start &> /dev/null
}

remove_cmd()
{
	echo "  - Reverting printers config"

	rm -rf /etc/cups/ppd/COPY3212.ppd

	service cups stop &> /dev/null

	if [ -f /etc/cups/printers.conf.bkp ]; then
		mv /etc/cups/printers.conf.bkp /etc/cups/printers.conf
	fi

	service cups start &> /dev/null
}

case $key in

	-i|--install)
	SCRIPTDIR="$2"
	install_cmd $SCRIPTDIR
	exit 0
	;;

	-r|--remove)
	remove_cmd
	exit 0
	;;

	*)
	echo "Unknonw option"
	exit 1

esac


